blank_issues_enabled: false
contact_links:
  - name: WorkflowLab Community Support
    url: https://github.com/WorkflowLabHQ/workflowlab-template/discussions
  - name: WorkflowLab Documentation
    url: https://workflowlab.com/docs
